apiVersion: v2
name: infra
description: A Helm chart that installs cert-manager, ingress-nginx, and other components.
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: cert-manager
    version: "v1.15.3"
    repository: "https://charts.jetstack.io"
  - name: ingress-nginx
    version: "4.11.2"
    repository: "https://kubernetes.github.io/ingress-nginx"