# Default values for infra.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

clusterIssuer:
  create: true
  email: "yuli@2bcloud.io"

cert-manager:
  crds:
    enabled: true

ingress-nginx:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
      externalTrafficPolicy: Local
    allowSnippetAnnotations: true