{{- if .Values.secretProviderClass.create -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.workloadName }}-sync"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "infra.labels" . | nindent 4 }}
spec:
  parameters:
    clientID: {{ .Values.workloadClientId | quote }}
    keyvaultName: {{ .Values.keyvaultName | quote }}
    objects: |
      array:
        - |
          objectName: azureStorageConnectionString
          objectType: secret              # object types: secret, key, or cert
        - |
          objectName: keysEncryptionKey
          objectType: secret
        - |
          objectName: queueConnectionString
          objectType: secret
    tenantId: {{ .Values.tenantId | quote }}
    usePodIdentity: "false"
  provider: azure
  secretObjects:
  # create a regular secret for queueConnectionString
  - data:
    - key: queueConnectionString
      objectName: queueConnectionString
    secretName: imagebatch-secret
    type: Opaque
{{- end }}