{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.workloadName | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "infra.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadClientId | quote }}
  {{- with .Values.serviceAccount.annotations }}
  #annotations:
  #  {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}