{{- if .Values.clusterIssuer.create -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    helm.sh/hook: "post-install"
    helm.sh/hook-weight: "5"
  name: cert-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.clusterIssuer.email | quote }}
    privateKeySecretRef:
      name: "letsencrypt-prod-secret"
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}