{{- if .Values.secretProviderClass.create -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.workloadName }}-sync"
  namespace: "default"
  labels:
    {{- include "infra.labels" . | nindent 4 }}
spec:
  parameters:
    clientID: {{ .Values.workloadClientId | quote }}
    keyvaultName: {{ .Values.keyvaultName | quote }}
    objects: |
      array:
        - |
          objectName: azureStorageConnectionString
          objectType: secret              # object types: secret, key, or cert
        - |
          objectName: keysEncryptionKey
          objectType: secret              # object types: secret, key, or cert
    tenantId: {{ .Values.tenantId | quote }}
    usePodIdentity: "false"
  provider: azure
{{- end }}