{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "infra.serviceAccountName" . }}
  #namespace: "default"
  labels:
    {{- include "infra.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceAccount.workloadClientId | quote }}
  {{- with .Values.serviceAccount.annotations }}
  #annotations:
  #  {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
